LGroup.ASPNET.MVC.Course/LGroup.SisAmigos.UI.Web/LGroup.SisAmigos.UI.Web/Controllers/AmigoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

/* * 
    Desde 2008 o que tem de mais TOP para fazer acesso a dados Microsoft é o Entity Framnework (EF)
    no VS2013 temos disponiveis aa versóes 5.0 e 6.x
    ==> É um EDMX (EF) por banco de dados
    Nome mais senior - geramos o EDMX através da estratégia DataBase First (primeiro montamos o banco de dados
    e depois geramos o EF)
    Subimos o diretório para memória para visualizar o Entity Framework
 * */
using LGroup.SisAmigos.UI.Web.DataAccess;

/* *
    Quando instalamos o visual studio 2013, vem como padrao o MVC 5.0
    uma novidade do 2013 agora temos um unico template de criaçao de projetos web >> ASP.NET ONE. 
    Todos os 3 aspnets foram integrados em 1 único projeto
    WEB FORMS (lixo), MVC (novo) e WEB API (serviços)
 * */
namespace LGroup.SisAmigos.UI.Web.Controllers
{
    /* *
        A classe controladora serve para declarar as paginas que queremos abrir,
        navegar, exibir para o usuario. É aqui dentro que criamos os apelidos das páginas
        e programaremos as páginas (acesso a banco, negocios, etc)
        nunca matar a palavra controller. É uma convenção, é um padrao de nomenclatura interno asp.net.
        Sem ele dá erro
     * */
    public class AmigoController : Controller
    {
        /* *
            sempre que quisermos abrir páginas, temos que criar apelidos pra essas páginas
            nome => ACTION OU AÇÃO

            antes de criar as paginas(html, css, js), primeira coisa que temos que fazer são
            as actions, cada  action vai ser responsavel por gerar, abrir uma pagina
         * */
        public ActionResult Listar()
        {
            /* *
                Criamos um objeto (variavel) apontando a classe de conexao (Contexto)
                do EF (mapeamento e representaçao de banco de dados)
                Dica:
                para descobrir o nome da classe de conexao, digitar ENTITIES. Há uma unica palavra NOMEDOBANCOEntities
               Ex.:
                MICROSOFT -> MICROSOFTEntities
                NETCODERS -> NETCODERSEntities
            * */
            var conexao = new AGENDAEntities();

            /* *
                Demos um select * from tb_amigo, pegamos todos os registros e descemos para View
                Eh o comando ToList() que abre a conexao com o BD e levou o comando
                SELECT (TSQL) para o servidor de banco de dados
            * */
            var amigos = conexao.TB_AMIGO.ToList();

            /* *
                podemos navegar no projeto mesmo sem ter paginas. É a técnica do ASPNET MVC chamada
                de routing(rotas), criamos url amigaveis pra abrir as páginas

                a pagina que ele tenta abrir tem o mesmo nome da action(Listar.cshtml).
                quando mandamos o comando return view() eh nesse momento que ele abre a pagina e devolve pro
                navegador

                Uma das formas de descer os dados para view eh através da técnica chamada MODEL BINDING
                passamos os dados dentro do comando view
                Via MODEL BINDING podemos descer dados complexos (lista de registros, new numa classe qualquer) e até 
                mesmo dados simples (primitivos) int, datetime, boolen soh dah pra descer uma unica informação via MODEL BINDING
            * */
            return View(amigos);
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        /* *
             o terceiro parametro eh sempre o id, pois foi definido lá no ROUTECONFIG(rota padrão), a única forma 
             de colocar outro nome eh alterado lá no routeconfig de ID para qualquer outro nome
         * */
        public ActionResult Editar(Int32 id)
        {
            //atraves do ID que veio da tela de listar, temos que dar um select na tabela e trazer o restante
            //dos campos (nome, email, telefone e data)
            var conexao = new AGENDAEntities();

            //o comando FIND do EF busca sempre o campo que eh chave primária (PK)
            //SELECT * FROM TB_AMIGO WHERE ID_AMIGO = ID
            var amigo = conexao.TB_AMIGO.Find(id);

            //além de levar para tela os dados do amigo temos que levar também os dados da table de sexo
            var sexos = conexao.TB_SEXO.ToList();

            //como já enviamos uma informacao via MODEL BINDING já queimou o cartucho
            //tudo que for informação secundaria, complementar descemos via VIEWBAG
            //temos 3 formas de descer dados para tela
            //1 >> MODEL BINDING = Pra propria TELA, dados principais da tela (AMIGO)
            //2 >> VIEWBAG = Pra propria TELA, dados secundarios (titulo, txt botao, rodapé)
            //3 >> TEMPDATA = Pra outra TELA

            //o VIEWBAG também eh exclusivo do MVC, também eh temporario (como tempdata)
            //cuidado com o viewbag, ele eh do tipo DYNAMIC (nao tem intellisense) eh na raça
            //ele soh verifica se o que esta lá dentro eh certo ou errado quando for compilar

            //para carregarmos um combobox (dropdownlist) a partir do controller temos que usar
            //a classe selectlist (exclusiva para carregamento do combo)
            //1 >> Dados que vao dentro do combo
            //2 >> campo que eh chave primaria (value) (numero oculto por tras do campo)
            //3 >> campo que eh descricao, o texto que vai aparecer para o usuario
            //4 >> campo onde falamos o sexo que vai selecionado, se 1-fem se 2-masc
            ViewBag.ListaSexos = new SelectList(sexos, "ID_SEXO", "DS_SEXO",amigo.ID_SEXO);

            //Após trazer o registro da table, levamos ele via MODEL BINDING la na tela de EDITAR
            return View(amigo);
        }

        /* *
            Normalmente criamdos duas actions por página (Cadastrar e Editar)
            >> 1 action para abrir a tela e levar dados para ela
            >> 1 action para resgatar os dados da tela (dos campos de preenchimento)
            GET => LEITURA => ABERTURA DE TELAS
            POST => GRAVAÇÃO => CADASTRO OU EDIÇÃO

            MVCPOSTACTION4 para criar actions que resgatam os dados da tela 
            Para pegar os campos da tela aqui dentro da action, uma das formas
            eh criar parametros de entrada. Um parametro de entrada para cada campo 
            que você quiser capturar o conteudo. Ele internamente utiliza o NAME(HTML)
            Ele internamente faz um REQUEST (FORM E QUERYSTRING)
            Podemos pegar quantos e quais campos da tela quisermos(não eh obrigatório pegar todos)
        * */
        [HttpPost]
        public ActionResult Cadastrar(String nome, String email, String telefone, DateTime data, Int32 sexo)
        {
            var conexao = new AGENDAEntities();

            //criamos uma variável apontando para tabela de amigos
            //fizemos um INSERT INTO via EF
            var novoAmigo = new TB_AMIGO();

            //DATA MAPPER é um nome bonito para pegar dados de um local e levar pra outro, movimentação de dados
            novoAmigo.NM_AMIGO = nome;
            novoAmigo.DS_EMAIL = email;
            novoAmigo.NR_TELEFONE = telefone;
            novoAmigo.DT_NASCIMENTO = data;
            novoAmigo.ID_SEXO = sexo;

            //Manda adicionar o registro na tabela e o salva
            conexao.TB_AMIGO.Add(novoAmigo);
            conexao.SaveChanges();

            /* * 
                Sempre que quisermos levar dados de uma tela para outra (action) pra outra, utilizar
                um recurso exclusivo do MVC chamado TEMPDATA 
                Podemos tanto armazenar dados simples (nome, email) quanto dados complexos (lista de registros
                de uma tabela). Tudo que jogarmos dentro do TEMPDATA conseguimos visualizar de qualquer local
                do projeto. São informaçoes globais!
            * */

            //Criamos uma variável dentro do TEMPDATA(NOME, CONTEÚDO)   
            TempData.Add("SUCESSO","Amigo Cadastrado com Sucesso!");

            //O Response.Redirect aqui no MVC é o RedirectToAction()
            //assim que ele cadastrar o amigo, o levamos de volta para a tela de listar
            return RedirectToAction("Listar");
        }

        /* * 
            criamos uma action post para pegar os dados da tela para editar
            1 action para abrir a tela (levar dados para tela)
            1 action para pegar os dados da tela (vai e volta)

            MVCPOSTACTION4 + tab + tab já monta uma action POST 

            Podemos pegar os dados dos campos da tela de 2 formas
            NAME >>   CAMPO A CAMPO (CADASTRAR)
            FORMCOLLECTION >> Ele sobe o conteúdo de todos os campos de uma única vez. 
            Mais inteligente, mais prático e mais fácil
         * */
        [HttpPost]
        public ActionResult Atualizar(FormCollection dadosTela)
        {
            //Temos que pegar os dados que vieram da tela dentro de formcollection
            //(coleção de campos) e enviar para tela 

            //criamos uma variavel de conexao com o banco de dados através do EF
            var conexao = new AGENDAEntities();
            
            //DATA MAPPER (movimentacao/MAPEAMENTO de dados)
            //cuidado com o formcollection, todos os dados que vem dentro dele vem em formato de "STRING"
            //CONVERT (INT32, DATETIME)
            var codigo = Convert.ToInt32(dadosTela["codigo"]);

            //SELECT * FROM TB_AMIGO WHERE ID_AMIGO = CODIGODATELA
            var amigo = conexao.TB_AMIGO.Find(codigo);

            //fizemos o data mapper dos dados
            amigo.NM_AMIGO = dadosTela["nome"];
            amigo.DS_EMAIL = dadosTela["email"];
            amigo.NR_TELEFONE = dadosTela["telefone"];
            amigo.DT_NASCIMENTO = Convert.ToDateTime(dadosTela["data"]);
            amigo.ID_SEXO = Convert.ToInt32(dadosTela["sexo"]);

LGroup.ASPNET.MVC.Course/LGroup.SisAmigos.UI.Web/LGroup.SisAmigos.UI.Web/Views/Amigo/Cadastrar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>..:: SISAMIGOS 1.0 ::..</title>
</head>
<body>
    <header>
        <div>
            <h1>..:: Cadastro de Amigos ::..</h1>
        </div>
    </header>
    
    <section>
        <div>
            <!--Todos os campos de preenchimento de tela (formulario) devem ficar dentro da tab <form>-->
            <form method="post">
                <div>
                    <label for="nome">Nome</label>
                    <!--sempre colocar o Name e o ID, algums recursos funcionam emcima do name e outros do id
                        id - é pro navegador, pro JavaScript
                        name - é pro C#, pro servidor (MVC) -->
                    <input type="text" name="nome" id="nome" autofocus="autofocus" />
                </div>
                <div>
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email" placeholder="informe um e-Mail comercial" size="30" />
                </div>
                <div>
                    <label for="telefone">Telefone</label>
                    <input type="tel" name="telefone" id="telefone"/>
                </div>
                <div>
                    <label for="data">Data de Nascimento</label>
                    <input type="date" name="data" id="data" />
                </div>
                <div>
                    <label for="sexo">Sexo</label>
                    <select name="sexo" id="sexo">
                        <option value="0">Selecione...</option>
                        <option value="1">Feminino</option>
                        <option value="2">Masculino</option>
                    </select>
                </div> 
                @* comentários em razor (C#) não são visíveis no navegador eles só são visiveis no Visual Studio *@
                <div>
                    <input type="reset" name="limpar" id="limpar" value="Limpar" />
                    <input type="submit" name="cadastrar" id="cadastrar" value="Cadastrar" />
                </div>
            </form>
        </div>
    </section>

    <footer>
        <div>
            <p>&copy; Todos os Direitos Reservados ao <strong>LGROUP</strong></p>
        </div>
    </footer>
</body>
</html>

LGroup.ASPNET.MVC.Course/LGroup.SisAmigos.UI.Web/LGroup.SisAmigos.UI.Web/Views/Amigo/Editar.cshtml
@* fizemos o recebimento dos dados que estão vindo do controller *@

@using LGroup.SisAmigos.UI.Web.DataAccess
@model TB_AMIGO

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>..:: SISAMIGOS 1.0 ::..</title>
</head>
<body>
    <header>
        <div>
            <h1>..:: Edição de Amigos ::..</h1>
        </div>
    </header>

    @* O MVC eh hibrido, podemos desenhar a tela de duas formas:
        1- html puro >> cadastrar
        2- html helpers >> editar
    *@
    <section>
        <div>
            @* vamos chegar ao mesmo resultado final da pagina de cadastrar utilizando html helpers
                eh uma forma de montar a tela utilizando C#(razor)
            *@
            @* o comando using abre e fecha automaticamente as tags. Ele vai abrir e fechar o <form></form>*@
            @using (Html.BeginForm("Atualizar","Amigo", FormMethod.Post))
            {
                @* No update precisamos do codigo do amigo, para nao ter que colocar um textbox de codigo
                    (tosco), para que ele não fique visivel na tela, criamos um campo oculto *@
                @Html.Hidden("codigo", Model.ID_AMIGO)
                
                <div>
                    @* quando utilizamos o label temos que passar dois parametros
                        1 - label for (campo foco)
                        2 - texto do label
                        *@
                    @Html.Label("nome", "Nome")
                    @*ao utilizar o html helper de textbox passamos 3 parametros 
                        1-nome, id do campo
                        2-texto que queremso mostrar dentro do campo
                        3-Eh onde settamos os atributos html daquele elemento (campo)
                        sempre que encontrar um paramentro chamado htmlAttributes, mete o new{} e sai
                        colocando o nome e conteudo do attr*@
                    @Html.TextBox("nome",Model.NM_AMIGO, new {autofocus = "autofocus"})
                </div>
                <div>
                    @Html.Label("email","Email")
                    @Html.TextBox("email", Model.DS_EMAIL, new {placeholder = "Informe um email comercial",size="30",type="email" })
                </div>
                <div>
                    @Html.Label("telefone","Telefone")
                    @* quando colocamos o helper textbox o type eh sempre text
                        pra sair algum type diferente settar na unha (html attibutes) *@
                    @Html.TextBox("telefone", Model.NR_TELEFONE, new { type = "tel"})
                </div>
                <div>
                    @* os campos que nao tiveram html helper (razor) tem que ir na raça utilizando hmtl puro *@
                    @Html.Label("Data","Data de Nascimento")

                    @* o segundo parametro do textbox eh para exibir uma informaçao dentro do campo
                        mandamos exibir o conteudo do campo DT_NASCIMENTO que chegou lá em cima (MODEL BINDING)*@
                    @* o terceiro parametro eh uma novidade que tem desde o MVC4, é onde conseguimos mudar o formato
                        do campo, mudamos o formato da data para ANO-MES-DIA (AMERICANO) *@
                    @Html.TextBox("Data", Model.DT_NASCIMENTO, "{0:yyy-MM-dd}", new { type="date"})
                </div>
                <div>
                    @Html.Label("sexo","Sexo")
                    @* montamos um dropdown(combo) a partir do viewbag (dados secundários) *@
                    @* como o viewbag é dynamic ele nao sabe o que tem lá dentro. No dropdown somos obrigados
                        a falar que temos um SELECTLIST. Você foi obrigado a fazer uma conversão e deixar
                        bem claro o que vai vir dentro do VIEWBAG *@
                    @Html.DropDownList("sexo", ViewBag.ListaSexos as SelectList)
                </div>
                @* o resultado final da pagina é sempre html. Os html helpers viram html puro *@
                <div>
                    <input type="reset" name="limpar" id="limpar" value="Limpar" />
                    <input type="submit" name="atualizar" id="atualizar" value="Atualizar" />
                </div>
            }
        </div>
    </section>

    <footer>
        <div>
            <p>&copy; Todos os Direitos Reservados ao <strong>LGROUP</strong></p>
        </div>
    </footer>
</body>
</html>

LGroup.ASPNET.MVC.Course/LGroup.SisAmigos.UI.Web/LGroup.SisAmigos.UI.Web/Views/Amigo/Listar.cshtml
@* Temos que interceptar os dados que vieram da action aqui dentro da view, temos que fazer o model binding
    aqui na view para pegar a lista de amigos *@

@using LGroup.SisAmigos.UI.Web.DataAccess

@* quando fizermos o model binding colocar o M em minúsculo 
    model -> pra receber os dados via model bindng ( a grosso modo) eh como se fosse um parametro
    de entrada da tela) quem for chamar ela vai ter que passar pra dentro dela uma lista de amigos
    MODEL -> para manipular os dados que entao vieram via MODEL BINDING
    O nome mais popular eh tipagem da view (tela)
    DICA DE OTIMIZAÇÃO:
    Sempre que tiver List trocar por IEnumerable
        List -> Leitura de Gravação
    Gravação -> Somente Leitura
*@
@model IEnumerable<TB_AMIGO>

<!--
    Criamaos uma view para cada action
    CSHTML siginifica que eh uma pagina em html que está sendo programada em C#
    -->
@{
    //sempre que encontrarmos algum codigo que começa com @ significa
    //que eh um codigo em C# == RAZOR
    //Razor eh o nome gourmetizado para o codigo de servidor, pro nosso codigo em C#
    //se tivermos uma pagina mestre(pai) MASTER PAGE, eh dentro do atributo layout que 
    //passariamos o cominho dela
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>..:: SISAMIGOS 1.0 ::..</title>
</head>
<body>
    <header>
        <div>
            <h1>..:: Lista de Amigos ::..</h1>
        </div>
    </header>

    <section>
        <div>
            <table>
               <thead>
                   <tr>
                       <th>Excluir</th>
                       <th>Editar</th>
                       <th>Código</th>
                       <th>Nome</th>
                       <th>eMail</th>
                       <th>Telefone</th>
                       <th>Data de Nascimento</th>
                   </tr>
               </thead>
                <tbody>
                    @* Fizemos um looping para percorrer todos os registros que vieram do BD via Model Binding 
                        Cada linha da tabela vai virar uma <TR> = Linha do Grid 
                        O MODEL em maiusculo eh um alias (referencia) pra pegar os dados que chegaram
                        lá em cima ^^^^^^^^^^^ *@
                    @foreach (var amigo in Model)
                    {
                        <tr>
                            <td></td>
                            <td>
                                @*  essa eh a rota (forma de navegar padrao)
                                    podemos mandar no maximo 3 parametros
                                    {controller}/{action}/{id} = Numero que queremos levar para ACTION 
                                *@
                                <a href="/Amigo/Editar/@amigo.ID_AMIGO">
                                    Editar
                                </a>
                            </td>
                            <td>@amigo.ID_AMIGO</td>
                            <td>@amigo.NM_AMIGO</td>
                            <td>@amigo.DS_EMAIL</td>
                            <td>@amigo.NR_TELEFONE</td>
                            <td>@amigo.DT_NASCIMENTO.ToShortDateString()</td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="7">Total : @Model.Count()</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </section>

    <footer>
        <div>
            <p>&copy; Todos os Direitos Reservados ao <strong>LGROUP</strong></p>
        </div>
    </footer>
    
    @* So vamos exibir o bloco de script na pagina se tiver mensagens dentro do tempdata *@
    @if (TempData["SUCESSO"] != null){
    <script>
        //Exibimos uma mensagem de sucesso que veio lá da tela de cadastrar (JS)
        //Assim que voce termina de ler o TEMPDATA ele se AUTO REMOVE (AUTO LIMPA)
        //Por isso o nome TEMPDATA pois armazenamos dados temporários que não vao ficar pra sempre na memória
        alert('@TempData["SUCESSO"]');
    </script>
    }
</body>
</html>